### ISSUE TITLE
seahub使用Nginx服务器启动失败

### ISSUE THREAD

**Issue by MonsterWang** [haiwen/seahub#1134]
System Env：
CentOS7 x86_64
seafile server 5.1.1 64位
MySQL5.7.12
使用MySQL，安装过程中没有问题，使用fastcgi模式启动时出错，出错信息如下：
`
Traceback (most recent call last):
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/base.py", line 444, in execute
    self.check()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 1205, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/base.py", line 1282, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 934, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 207, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
    return connection.validation.check_field(self, **kwargs)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/validation.py", line 18, in check_field
    field_type = field.db_type(connection)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1193, "Unknown system variable 'storage_engine'")
Error:Seahub failed to start.
`

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
