### ISSUE TITLE
seahub return 500 on each request after upgrade from 5.1.1 to 5.1.2

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1153]
After upgrade to 5.1.2 seahub can't find one of css files:

```
Traceback (most recent call last):
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/seahub/base/decorators.py", line 39, in _decorated
    return func(request, *args, **kwargs)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/seahub/views/__init__.py", line 884, in libraries
    }, context_instance=RequestContext(request))
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 210, in render
    return self._render(context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/cache.py", line 94, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 172, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 166, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/css.py", line 23, in split_contents
    filename = self.get_filename(basename)
  File "/srv/seafile/seafile-pro-server-5.1.2/seahub/thirdpart/django_compressor-1.4-py2.7.egg/compressor/base.py", line 137, in get_filename
    self.finders and " or with staticfiles." or "."))
UncompressableFileError: 'assets/css/backbone.8807a4408f24.css' could not be found in the COMPRESS_ROOT '/srv/seafile/seafile-pro-server-5.1.2/seahub/media' or with staticfiles.
```
There is no such file "backbone.8807a4408f24.css" at '/srv/seafile/seafile-pro-server-5.1.2/seahub/media/assets/css/'
```
ls -l /srv/seafile/seafile-pro-server-5.1.2/seahub/media/assets/css/
total 96
-rw-rw-r-- 1 seafile seafile   846 Apr 21 09:08 backbone.css
-rw-rw-r-- 1 seafile seafile   846 Apr 21 09:08 backbone.e3c60fd65a27.css
-rw-rw-r-- 1 seafile seafile  7805 Apr 21 09:08 magnific-popup.656241b2c8ed.css
-rw-rw-r-- 1 seafile seafile  7805 Apr 21 09:08 magnific-popup.css
-rw-rw-r-- 1 seafile seafile   613 Apr 21 09:08 select2.2ca61b76e220.png
-rw-rw-r-- 1 seafile seafile 19730 Apr 21 09:08 select2-3.5.2.b9d0598b4e1c.css
-rw-rw-r-- 1 seafile seafile 19457 Apr 21 09:08 select2-3.5.2.css
-rw-rw-r-- 1 seafile seafile   394 Apr 21 09:08 select2.custom.9fe18e0ae58c.css
-rw-rw-r-- 1 seafile seafile   394 Apr 21 09:08 select2.custom.css
-rw-rw-r-- 1 seafile seafile   613 Apr 21 09:08 select2.png
-rw-rw-r-- 1 seafile seafile  1849 Apr 21 09:08 select2-spinner.7b9776076d5f.gif
-rw-rw-r-- 1 seafile seafile  1849 Apr 21 09:08 select2-spinner.gif
-rw-rw-r-- 1 seafile seafile   845 Apr 21 09:08 select2x2.49e3f0060186.png
-rw-rw-r-- 1 seafile seafile   845 Apr 21 09:08 select2x2.png
``` 
It's can be fixed by creating symbolic link 
```backbone.8807a4408f24.css -> backbone.e3c60fd65a27.css```

**Comment by freeplant** [comment]
This is a config issue. Make sure seafile-server-latest point to the right version and you can also try restart memcached.

**Comment by khorkin** [comment]
restart memcached fix this problem. Thank you.
