### ISSUE TITLE
Users with umlauts in name breaks group management

### ISSUE THREAD

**Issue by sjansen1** [haiwen/seahub#1171]
Hi,

today i added some users with Umlauts (ü, ö , ä) in their display name. Try to add them does nothing, after that group management for that group is broken and always fails with "failure" showing user list o try to manage the group. There is no way to manage this groups anymore.

In seahub_django_request.log i can find this error:

`2016-05-03 14:30:14,978 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /sf/api/v2.1/groups/9/members/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/response.py", line 71, in rend                                       ered_content
    ret = renderer.render(self.data, media_type, context)
  File "/opt/seafile/seafile-server-5.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/renderers.py", line 104, in re                                       nder
    separators=separators
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
`

I tested this with Seafile Pro 5.1.2 and Seafile Community 5.1.1. Both on Ubuntu 16.04 with MySQL 5.7, memcache and nginx.

**Comment by shoeper** [comment]
I cannot reproduce this. Works without problems here on Pro 5.1.3.

Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.
