### ISSUE TITLE
seahub failed with trace when accessing /sys/log/fileaudit/ with removed repo

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1208]
Hi,
seahub failed with trace when accessing /sys/log/fileaudit/ with removed repo on repo-download-sync operations
```
select * from RepoTrash where repo_id= '40b5476b-416b-462c-9667-631a768869d1'\G
*************************** 1. row ***************************
  repo_id: 40b5476b-416b-462c-9667-631a768869d1
repo_name: INC000005229704
  head_id: 1135ee09bf5d7c4d4f5c2e801b44a7f47005f7ba
 owner_id: USER@EXAMPLE.COM
     size: 0
   org_id: -1
 del_time: 1464077159
```
```
select * from FileAudit where eid = 4239594\G
*************************** 1. row ***************************
      eid: 4239594
timestamp: 2016-05-24 07:57:02
    etype: repo-download-sync
     user: USER@EXAMPLE.COM
       ip: $IP$
   device: USER@
   org_id: -1
  repo_id: 40b5476b-416b-462c-9667-631a768869d1
file_path: /
```

```
Internal Server Error: /sys/log/fileaudit/
Traceback (most recent call last):
  File "/srv/seafile/seafile-pro-server-5.1.4/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/seafile-pro-server-5.1.4/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/seafile/seafile-pro-server-5.1.4/seahub/seahub/base/decorators.py", line 25, in _decorated
    return func(request, *args, **kwargs)
  File "/srv/seafile/seafile-pro-server-5.1.4/seahub-extra/seahub_extra/sysadmin_extra/views.py", line 131, in sys_log_file_audit
    ev.file_or_dir_name = ev.repo.name if ev.file_path == '/' else os.path.basename(ev.file_path.rstrip('/'))
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by shoeper** [comment]
5.1.5 will be released, soon. Afaik it fixes this issue.
