### ISSUE TITLE
500 Error and django trace when requesting api2/repos/repoid/update-link for deleted repo

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1368]
Hi,
500 error appeared when customer ask for update file for removed repo.

```
2016-09-26 10:37:42,509 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/repos/e5b67c26-b890-492a-860c-04ac3e8f5680/update-link/
Traceback (most recent call last):
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "./seahub/api2/views.py", line 1209, in get
    if check_folder_permission(request, repo_id, parent_dir) != 'rw':
  File "./seahub/views/__init__.py", line 116, in check_folder_permission
    return seafile_api.check_permission_by_path(repo_id, path, username)
  File "/srv/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/seaserv/api.py", line 582, in check_permission_by_path
    return seafserv_threaded_rpc.check_permission_by_path(repo_id, path, user)
  File "/srv/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/srv/seafile/seafile-server-latest/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 25, in _fret_string
    raise SearpcError(dicts['err_msg'])
SearpcError: Failed to get repo
```

I have thousands such errors from one customer, it's looks like a seadroid issue
User-agent: Dalvik/2.1.0 (Linux; U; Android 7.0; Nexus 5X Build/NRD90R
Anyway seahub should return 404 repo not found instead 500 and  trace back.

**Comment by freeplant** [comment]
Fixed the Seahub part in https://github.com/haiwen/seahub/pull/1383
