### ISSUE TITLE
seahub-6.0.2 (pro) 500 error when searching unexisting user

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1384]
Seahub traced and return 500 error page.
Steps to reproduce:
1. Go admin page
2. search any unexistence use, abcabcabc as example:
```
Internal Server Error: /useradmin/search/
Traceback (most recent call last):
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./seahub/base/decorators.py", line 26, in _decorated
    return func(request, *args, **kwargs)
  File "./seahub/views/sysadmin.py", line 1510, in user_search
    'extra_user_roles': extra_user_roles,
UnboundLocalError: local variable 'extra_user_roles' referenced before assignment

Request repr(): 
<WSGIRequest
path:/useradmin/search/,
GET:<QueryDict: {u'email': [u'abcabcabc']}>,
...
```

Possible fix is define extra_user_roles:
```
--- sysadmin.py-orig	2016-10-17 10:34:34.000000000 +0300
+++ sysadmin.py	2016-10-31 12:07:43.155526980 +0300
@@ -1469,2 +1469,3 @@
     users = []
+    extra_user_roles = []
     for user_email in user_emails:
```

**Comment by freeplant** [comment]
Fixed in https://github.com/haiwen/seahub/pull/1385
