### ISSUE TITLE
Uninformative error message when user registration fails

### ISSUE THREAD

**Issue by zaudo** [haiwen/seahub#1387]
Using Seafile Pro Server 6.0.2 on CentOS 7. When all the available users for the license has been exhausted, if a user tries to sign up for a new account, they get a generic error:

> Sorry, but the requested page is unavailable due to a server hiccup

This error message does not match the Seafile site design (it's just plain text).

When I upgraded the license, the error no longer occurs. But they should get a better error message, for example:

> The registration could not be completed due a restriction in the licensing. Please contact your administrator for assistance.

And the error message should be on the Seafile site design.

Traceback shows the following:

```
2016-11-02 04:53:18,952 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/thirdpart/registration/views.py", line 197, in register
    new_user = backend.register(request, **form.cleaned_data)
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/seahub/base/accounts.py", line 456, in register
    send_email=config.REGISTRATION_SEND_MAIL)
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/thirdpart/registration/models.py", line 93, in create_inactive_user
    send_email, is_active=False)
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/thirdpart/registration/models.py", line 80, in create_email_user
    user = User.objects.create_user(username, password, False, is_active)
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/seahub/base/accounts.py", line 51, in create_user
    return self.get(email=email)
  File "/var/www/example.com/seafile-pro-server-6.0.2/seahub/seahub/base/accounts.py", line 89, in get
    raise User.DoesNotExist, 'User matching query does not exits.'
DoesNotExist: User matching query does not exits.
```

**Comment by freeplant** [comment]
It will be fixed in version 6.0.6.
