### ISSUE TITLE
Failed to cache (set/get) WOPI_ACCESS_TOKEN_EXPIRATION due to memcached key length limit

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1397]
Hi,
django traced and failed to set/get WOPI_ACCESS_TOKEN_EXPIRATION for files with long full path, length more than 250:
```
Internal Server Error: /api2/wopi/files/04a320db40ac5764b2075352a4625665d89d04e3
Traceback (most recent call last):
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub-extra/seahub_extra/wopi/views.py", line 139, in post
    seafile_api.lock_file(repo_id, file_path, request_user,
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/cache/backends/memcached.py", line 84, in get
    val = self._cache.get(key)
  File "/usr/lib/python2.7/site-packages/memcache.py", line 1002, in get
    return self._get('get', key)
  File "/usr/lib/python2.7/site-packages/memcache.py", line 948, in _get
    self.check_key(key)
  File "/usr/lib/python2.7/site-packages/memcache.py", line 1192, in check_key
    "Key length is > %s" % self.server_max_key_length
MemcachedKeyLengthError: Key length is > 250
```

The possible fix is using hash from filepath in seahub-extra/seahub_extra/wopi/views.py
```
@@ -4,6 +4,7 @@
 import logging
 import urllib2
 import requests
+import hashlib
 
 from rest_framework.views import APIView
 
@@ -126,8 +127,11 @@
             return HttpResponse(json.dumps({'error_msg': 'HTTP_X_WOPI_OVERRIDE missing'}),
                     status=401, content_type=json_content_type)
 
-        key_locked_by_OWA = '_'.join(['WOPI_LOCK',
-            repo_id, urlquote(file_path), 'locked_by_OWA'])
+        key_locked_by_OWA = hashlib.sha256(
+                '_'.join(['WOPI_LOCK', repo_id, urlquote(file_path), 'locked_by_OWA'])
+                ).hexdigest()
 
         if x_wopi_override in ('LOCK', 'REFRESH_LOCK'):
             if not is_locked:
```

**Comment by imwhatiam** [comment]
fixed, thanks for reporting.
