### ISSUE TITLE
Seafile pro 6.0.4 doesn't support utf-8 characters in filename when preview in MSOffice WebApp

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1416]
Hi, 
since 6.0.3/6.0.4 it's impossible to preview files with utf-8 characters via MS Office WebApp.
```
Internal Server Error: /api2/wopi/files/0d44546894d7bfd9eed04c95dbb59307c28f2434
Traceback (most recent call last):
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/Django-1.8.16-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/seafile-server-latest/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/seafile/seafile-server-latest/seahub-extra/seahub_extra/wopi/views.py", line 132, in post
    file_path_hash = hashlib.sha256(file_path).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-4: ordinal not in range(128)
```
file name is "Тест non-utf8 characters.xlsx"
Possible fix is:
```
--- /srv/seafile/seafile-server-latest/seahub-extra/seahub_extra/wopi/views.py-orig	2016-12-05 13:51:08.509619566 +0300
+++ /srv/seafile/seafile-server-latest/seahub-extra/seahub_extra/wopi/views.py	2016-12-05 13:51:32.764619004 +0300
@@ -129,7 +129,7 @@
             return HttpResponse(json.dumps({'error_msg': 'HTTP_X_WOPI_OVERRIDE missing'}),
                     status=401, content_type=json_content_type)
 
-        file_path_hash = hashlib.sha256(file_path).hexdigest()
+        file_path_hash = hashlib.sha256(file_path.encode('utf-8')).hexdigest()
         key_locked_by_OWA = '_'.join(['WOPI_LOCK',
                 repo_id, 'file_path_hash', file_path_hash, 'locked_by_OWA'])
```
it's bug affected 6.0.3 and 6.0.4 and was introduced by fix 
[fix] Failed to cache (set/get) WOPI_ACCESS_TOKEN_EXPIRATION due to memcached key length limit
I'm not sure do you use only 'utf-8' encoding when storing filename, may be we should detect encoding first.
Evgeny.

**Comment by imwhatiam** [comment]
Thanks for reporting, this is the bug fix: https://github.com/seafileltd/seahub-extra/pull/85

It is appreciated if you manually change the code and test it again.

**Comment by khorkin** [comment]
I already done it, before post bug.
