### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by ddatsh** [haiwen/seahub#1456]
centos 6, python 2.7 
seafile 5 or 6 , same problem
```
2017/01/11 09:36:06 [error] 1538#1538: *1 FastCGI sent in stderr: "" while reading response header from upstream, client: 192.168.1.104, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "192.168.1.102", referrer: "http://192.168.1.102/"
2017/01/11 09:36:06 [error] 1538#1538: *1 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/flup-1.0.2-py2.7.egg/flup/server/fcgi_base.py", line 558, in run
    protocolStatus, appStatus = self.server.handler(self)
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/flup-1.0.2-py2.7.egg/flup/server/fcgi_base.py", line 1118, in handler
    result = self.application(environ, start_response)
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/root/seafile-pro-server-5.1.11/pro/python/importlib-1.0.2-py2.6.egg/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/seafile-pro-server-5.1.11/seahub/seahub/utils/rooturl.py", line 40, in <module>
    (r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/root/seafile-pro-server-5.1.11/seahub/thirdpart/Django-1.8.10-py2.7.egg/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/seafile-pro-server-5.1.11/pro/python/importlib-1.0.2-py2.6.egg/importlib/__init__.py", line 37, in import_module
    __import__(name)
```

**Comment by lbosnjak** [comment]
Hi,

I've had a similar problem, did you check these ones?

yum install python-urllib3
or

[https://github.com/haiwen/seahub/issues/1100](url)

Leo

**Comment by ddatsh** [comment]
@lbosnjak yes,just because python-urllib3
