### ISSUE TITLE
Error 500 and django traceback when loading repos

### ISSUE THREAD

**Issue by Ashaman-** [haiwen/seahub#1691]
This started happening after a power outage. seaf-fsck.sh reports no errors.
Seafile clients that are already logged in do not show list of repos, but continue to sync normally. Impossible to connect new seafile clients mobile or desktop. Error has persisted versions 6.0.8-6.1.1. LDAP backend for users.

The following prints in the error log immediately after login when 'my libraries' attempt to load.
`2017-07-11 19:14:54,623 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api/v2.1/notifications/
Traceback (most recent call last):
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 378, in initial
    self.check_throttles(request)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 340, in check_throttles
    if not throttle.allow_request(request, self):
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/seahub/api2/throttling.py", line 129, in allow_request
    self.history = self.cache.get(self.key, [])
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/filebased.py", line 41, in get
    if not self._is_expired(f):
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/filebased.py", line 138, in _is_expired
    exp = pickle.load(f)
EOFError
2017-07-11 19:14:54,626 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api2/repos/
Traceback (most recent call last):
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 378, in initial
    self.check_throttles(request)
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/djangorestframework-3.3.2-py2.7.egg/rest_framework/views.py", line 340, in check_throttles
    if not throttle.allow_request(request, self):
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/seahub/api2/throttling.py", line 129, in allow_request
    self.history = self.cache.get(self.key, [])
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/filebased.py", line 41, in get
    if not self._is_expired(f):
  File "/var/lib/seafile/seafile-server-6.1.1/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/cache/backends/filebased.py", line 138, in _is_expired
    exp = pickle.load(f)
EOFError`

Please advise.

**Comment by freeplant** [comment]
remove /tmp/seahub_cache should solve the problem

**Comment by Ashaman-** [comment]
Thank you!!

**Comment by kartikagarwal799** [comment]
doesn't work for me...

**Comment by huyx1501** [comment]
I think it's a bug of Django.
If there is an(or more) empty file in /tmp/seahub_cache(May be some other place, I'm not sure) because of some reson, this issue will recurring.

 I fix this problem by modify the file "opt/seafile/seafile-server-6.3.4/seahub/thirdpart/django/core/cache/backends/filebased.py".

from
>        exp = pickle.load(f)
>        if exp is not None and exp < time.time():
>            f.close()  # On Windows a file has to be closed before deleting
>            self._delete(f.name)
>            return True
>        return False

to
>        try:
>            exp = pickle.load(f)
>            if exp is not None and exp < time.time():
>                f.close()  # On Windows a file has to be closed before deleting
>                self._delete(f.name)
>                return True
>            return False
>        except EOFError:
>            self._delete(f.name)
>            return True

Then restart seahub.
That works for me.
