### ISSUE TITLE
HTTP 500: ProgrammingError: column share_fileshare.permission does not exist

### ISSUE THREAD

**Issue by turlando** [haiwen/seahub#1707]
Seafile version: 6.1.1
Seahub version: 6.1.4
OS: FreeBSD 11.0
DB: PgSQL

**Steps to reproduce**:
* In the file browser open the preview of any document

**What happens**:
* For a PDF file:
  >Page unavailable
  >Sorry, but the requested page is unavailable due to a server hiccup.
  >Our engineers have been notified, so check back later.

* For a jpg image:
  >The image could not be loaded.

**Background**: I was running seafile 6.0.10 and seahub 6.0.13 before the upgrade. I eventually ran `manage.py syncdb`.

**Logs**:
* `seahub_django_request.log`
```
2017-07-16 13:51:52,986 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /lib/807392b2-3e36-4688-8d93-8a2de0810f87/file/seafile-tutorial.doc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/base/decorators.py", line 74, in _decorated
    return func(request, *args, **kwargs)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/views/file.py", line 385, in view_lib_file
    return _file_view(request, repo_id, path)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/views/file.py", line 581, in _file_view
    fileshare = l[0] if len(l) > 0 else None
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column share_fileshare.permission does not exist
LINE 1: ...are"."password", "share_fileshare"."expire_date", "share_fil...
```

**Comment by turlando** [comment]
Also going to the Links section causes this:

```
2017-07-16 13:55:42,266 [ERROR] django.request:256 handle_uncaught_exception Internal Server Error: /api/v2.1/share-links/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/www/haiwen/seafile-server/seahub/seahub/api2/endpoints/share_links.py", line 171, in get
    for fs in fileshares:
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column share_fileshare.permission does not exist
LINE 1: ...are"."password", "share_fileshare"."expire_date", "share_fil...
```

**Comment by shoeper** [comment]
Upgrade has not been performed properly. Please ask such questions in the forum.

Have a look at the major upgrade script. It'll run an SQL file from the upgrade folder to update the database accordingly. manage.py is not being used.

**Comment by turlando** [comment]
Thanks for the help!

I ran the `upgrade_6.0_6.1.sh` script, but it assumed I was using SQLite, not PgSQL. After having a look at the script I thought that a syncdb would fix it. It found diffs to be applied to the schema and updated it without problems.

**Comment by shoeper** [comment]
> Running minor-upgrade.sh will not help, right?

It mainly upgrades the symlink.

> PgSQL

PgSQL has never really been supported. I'd always recommend to use Seafile with MySQL / MariaDB in production.

> I ran the upgrade_6.0_6.1.sh script, but it assumed I was using SQLite, not PgSQL. 

As said, I'd have a look at the upgrade folder. There is an SQL file for the upgrade, make sure all changes have been applied.

**Comment by turlando** [comment]
1. `share_fileshare`
  * Query:
```
ALTER TABLE `share_fileshare` MODIFY token varchar(100);
ALTER TABLE `share_fileshare` ADD COLUMN `permission` varchar(50) NOT NULL DEFAULT 'view_download';
```
* DB:
```
seafile_seahub=# \d+ share_fileshare
                                                        Table "public.share_fileshare"
   Column    |           Type           |                          Modifiers                           | Storage  | Stats target | Description 
-------------+--------------------------+--------------------------------------------------------------+----------+--------------+-------------
 id          | integer                  | not null default nextval('share_fileshare_id_seq'::regclass) | plain    |              | 
 username    | character varying(255)   | not null                                                     | extended |              | 
 repo_id     | character varying(36)    | not null                                                     | extended |              | 
 path        | text                     | not null                                                     | extended |              | 
 token       | character varying(10)    | not null                                                     | extended |              | 
 ctime       | timestamp with time zone | not null                                                     | plain    |              | 
 view_cnt    | integer                  | not null                                                     | plain    |              | 
 s_type      | character varying(2)     | not null                                                     | extended |              | 
 password    | character varying(128)   |                                                              | extended |              | 
 expire_date | timestamp with time zone |                                                              | plain    |              | 
Indexes:
    "share_fileshare_pkey" PRIMARY KEY, btree (id)
    "share_fileshare_token_key" UNIQUE CONSTRAINT, btree (token)
    "share_fileshare_14c4b06b" btree (username)
    "share_fileshare_1abd88b5" btree (s_type)
    "share_fileshare_9a8c79bf" btree (repo_id)
    "share_fileshare_repo_id_348d56e711ef6a6a_like" btree (repo_id varchar_pattern_ops)
    "share_fileshare_s_type_644ae3465e93e1f1_like" btree (s_type varchar_pattern_ops)
    "share_fileshare_token_69d7c063d05e5c97_like" btree (token varchar_pattern_ops)
    "share_fileshare_username_410018e6fdfff61_like" btree (username varchar_pattern_ops)
Referenced by:
    TABLE "share_orgfileshare" CONSTRAINT "share_orgfi_file_share_id_7e98815f5df832f_fk_share_fileshare_id" FOREIGN KEY (file_share_id) REFERENCES share_fileshare(id) DEFERRABLE INITIALLY DEFERRED
```

2. `share_uploadlinkshare`
  * Query:
```
ALTER TABLE `share_uploadlinkshare` MODIFY token varchar(100);
```
  * DB:
```
seafile_seahub=# \d+ share_uploadlinkshare
                                                        Table "public.share_uploadlinkshare"
   Column    |           Type           |                             Modifiers                              | Storage  | Stats target | Description 
-------------+--------------------------+--------------------------------------------------------------------+----------+--------------+-------------
 id          | integer                  | not null default nextval('share_uploadlinkshare_id_seq'::regclass) | plain    |              | 
 username    | character varying(255)   | not null                                                           | extended |              | 
 repo_id     | character varying(36)    | not null                                                           | extended |              | 
 path        | text                     | not null                                                           | extended |              | 
 token       | character varying(10)    | not null                                                           | extended |              | 
 ctime       | timestamp with time zone | not null                                                           | plain    |              | 
 view_cnt    | integer                  | not null                                                           | plain    |              | 
 password    | character varying(128)   |                                                                    | extended |              | 
 expire_date | timestamp with time zone |                                                                    | plain    |              | 
Indexes:
    "share_uploadlinkshare_pkey" PRIMARY KEY, btree (id)
    "share_uploadlinkshare_token_key" UNIQUE CONSTRAINT, btree (token)
    "share_uploadlinkshare_14c4b06b" btree (username)
    "share_uploadlinkshare_9a8c79bf" btree (repo_id)
    "share_uploadlinkshare_repo_id_3ee7375b0d26d7c5_like" btree (repo_id varchar_pattern_ops)
    "share_uploadlinkshare_token_4728ed614a4cdb98_like" btree (token varchar_pattern_ops)
    "share_uploadlinkshare_username_7008430dc0e9278e_like" btree (username varchar_pattern_ops)
```
3. `institutions_institutionquota`
  * Query:
```
CREATE TABLE IF NOT EXISTS `institutions_institutionquota` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quota` bigint(20) NOT NULL,
  `institution_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `i_institution_id_2ca7c89373390e2c_fk_institutions_institution_id` (`institution_id`),
  CONSTRAINT `i_institution_id_2ca7c89373390e2c_fk_institutions_institution_id` FOREIGN KEY (`institution_id`) REFERENCES `institutions_institution` (`id`)
```
  * DB:
```
\d+ institutions_institutionquota
                                                 Table "public.institutions_institutionquota"
     Column     |  Type   |                                 Modifiers                                  | Storage | Stats target | Description 
----------------+---------+----------------------------------------------------------------------------+---------+--------------+-------------
 id             | integer | not null default nextval('institutions_institutionquota_id_seq'::regclass) | plain   |              | 
 quota          | bigint  | not null                                                                   | plain   |              | 
 institution_id | integer | not null                                                                   | plain   |              | 
Indexes:
    "institutions_institutionquota_pkey" PRIMARY KEY, btree (id)
    "institutions_institutionquota_a964baeb" btree (institution_id)
Foreign-key constraints:
    "institution_id_2ca7c89373390e2c_fk_institutions_institution_id" FOREIGN KEY (institution_id) REFERENCES institutions_institution(id) DEFERRABLE INITIALLY DEFERRED
```

4. `admin_log_adminlog`
  * Query:
```
CREATE TABLE IF NOT EXISTS `admin_log_adminlog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(254) NOT NULL,
  `operation` varchar(255) NOT NULL,
  `detail` longtext NOT NULL,
  `datetime` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `admin_log_adminlog_0c83f57c` (`email`),
  KEY `admin_log_adminlog_f7235a61` (`operation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
  * DB:
```
seafile_seahub=# \d+ admin_log_adminlog
                                                       Table "public.admin_log_adminlog"
  Column   |           Type           |                            Modifiers                            | Storage  | Stats target | Description 
-----------+--------------------------+-----------------------------------------------------------------+----------+--------------+-------------
 id        | integer                  | not null default nextval('admin_log_adminlog_id_seq'::regclass) | plain    |              | 
 email     | character varying(254)   | not null                                                        | extended |              | 
 operation | character varying(255)   | not null                                                        | extended |              | 
 detail    | text                     | not null                                                        | extended |              | 
 datetime  | timestamp with time zone | not null                                                        | plain    |              | 
Indexes:
    "admin_log_adminlog_pkey" PRIMARY KEY, btree (id)
    "admin_log_adminlog_0c83f57c" btree (email)
    "admin_log_adminlog_email_692496e4e4ee76b2_like" btree (email varchar_pattern_ops)
    "admin_log_adminlog_f7235a61" btree (operation)
    "admin_log_adminlog_operation_70f64a82ef3b649d_like" btree (operation varchar_pattern_ops)
```

---

So it seems that only steps 1 and 2 failed. Do you suggest running those queries by myself?

**Comment by shoeper** [comment]
Yes. Could be that the queries need to be customized to work with postgresql. Could be helpful for others if you share your solution in case it works.

**Comment by turlando** [comment]
This query fixes the issue. I can now see file previews again.

```
BEGIN;
ALTER TABLE share_fileshare ALTER COLUMN token TYPE varchar(100);
ALTER TABLE share_fileshare ADD COLUMN permission varchar(50) NOT NULL DEFAULT 'view_download';
ALTER TABLE share_uploadlinkshare ALTER COLUMN token TYPE varchar(100);
COMMIT;
```

I guess it failed because of the very different `ALTER TABLE` syntax in PgSQL.

Thanks a lot for the help!
