### ISSUE TITLE
move away from mysqldb for seahub mysql/ mariadb connections

### ISSUE THREAD

**Issue by schmittlauch** [haiwen/seahub#2139]
The python2 mysqldb module used by seahub for connecting to the MySQL database [has been removed](https://bugzilla.opensuse.org/show_bug.cgi?id=1074660) from openSUSE 15.0 and SuSE linux enterprise 15.0 repositories, on which I run my seahub installation, it doesn't even build anymore with pip.

the mysqldb python package is [quite old](https://pypi.org/project/MySQL-python/#history) and has seen its last release in 2014.
Are there any plans to provide another way to connect to MySQL/ MariaDB?

Are there even plans on migrating to python 3.x?

Below is a stacktrace of SeaHub failing to start without mysqldb:

```
2018-06-04 10:35:59,193 [ERROR] seahub.api2.authentication:134 authenticate_v2 error when save token v2:
Traceback (most recent call last):
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/seahub/api2/authentication.py", line 132, in authenticate_v2
    token.save()
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/seahub/api2/models.py", line 171, in save
    return super(TokenV2, self).save(*args, **kwargs)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'created_at' cannot be null")
```

**Comment by xiez** [comment]
mysqlclient is the recommended choice according to https://docs.djangoproject.com/en/1.11/ref/databases/#id8

We'll update the installation instructions accordingly. Thanks!

Python3 is not supported in near future.
