### ISSUE TITLE
IntegrityError: "Column 'created_at' cannot be null"

### ISSUE THREAD

**Issue by schmittlauch** [haiwen/seahub#2168]
When trying to upload files to my seafile installation via Seahub, these uploads fail with an unknown error.
The seahub.log log file gives the following error:

```
2018-06-18 08:15:19,685 [ERROR] seahub.api2.authentication:134 authenticate_v2 error when save token v2:
Traceback (most recent call last):
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/seahub/api2/authentication.py", line 132, in authenticate_v2
    token.save()
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/seahub/api2/models.py", line 171, in save
    return super(TokenV2, self).save(*args, **kwargs)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/seafile/haiwen/seafile-server-6.2.5/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
IntegrityError: (1048, "Column 'created_at' cannot be null")
```

I'm running the open source version of seafile-6.2.5 with a MariaDB backend and think that I ran all migrations when uograding between versions.
As the python mysql connector module I use the `mysqlclient` package.

Any pointers to what went wrong with my setup?

**Comment by shoeper** [comment]
It is unlikely that this is a bug. Use the [forum](https://forum.seafile.com/) for questions, please.
