### ISSUE TITLE
.doc preview: URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:579)>

### ISSUE THREAD

**Issue by MrMoronIV** [haiwen/seahub#2219]
Platform: Centos 7

As soon as I click on seafile-tutorial.doc in seahub I get:

in seahub.log
```
2018-07-22 13:31:47,821 [ERROR] root:1172 prepare_converted_html failed to add_office_convert_task:
Traceback (most recent call last):
  File "/seafile/seafile-server-latest/seahub/seahub/utils/__init__.py", line 1170, in prepare_converted_html
    add_office_convert_task(obj_id, doctype, raw_path)
  File "/seafile/seafile-server-latest/seahub/seahub/utils/__init__.py", line 1082, in real_func
    return delegate_func(*args)
  File "/seafile/seafile-server-latest/seahub/seahub/utils/__init__.py", line 1098, in delegate_add_office_convert_task
    ret = do_urlopen(url, data=data, headers=headers).read()
  File "/seafile/seafile-server-latest/seahub/seahub/utils/__init__.py", line 1299, in do_urlopen
    ret = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:579)>
```

Not sure what to do, I've deployed the cluster installation and all seems to be working fine, except for this. I've configured the background server on a separate server and is reachable over https with a valid certificate.

I already tried Collabolera, which worked at least from a technical viewpoint, but oh boy is that eating system resources and does it lack features. Would now at least like to enable the doc preview :)

Any help is appreciated.

**Comment by MrMoronIV** [comment]
If anyone is wondering, OFFICE_CONVERTOR_ROOT was set to http instead of https
