### ISSUE TITLE
Error while loading Traffic informations

### ISSUE THREAD

**Issue by Dr0lli** [haiwen/seahub#2330]
Seafile Pro Version: 6.3.4

Seafevent Config:

[DATABASE]
type = sqlite3
path = /opt/seafile/pro-data/seafevents.db

Error Message:

2018-09-02 21:31:09,185 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api/v2.1/admin/statistics/active-users/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/thirdpart/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/seahub/api2/endpoints/admin/statistics.py", line 47, in _decorated
    return func(view, request, start_time, end_time)
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/seahub/api2/endpoints/admin/statistics.py", line 120, in get
    data = get_user_activity_stats_by_day(start_time, end_time, get_time_offset())
  File "/opt/seafile/seafile-pro-server-6.3.4/seahub/seahub/utils/__init__.py", line 650, in get_user_activity_stats_by_day
    res = seafevents.get_user_activity_stats_by_day(session, start, end, offset)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/seafevents/statistics/db.py", line 93, in get_user_activity_stats_by_day
    rows = q.all()
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2643, in all
    return list(self)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/seafile/seafile-pro-server-6.3.4/pro/python/SQLAlchemy-1.1.3-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such function: convert_tz [SQL: u'SELECT date(convert_tz("UserActivityStat".timestamp, ?, ?)) AS timestamp, count(DISTINCT "UserActivityStat".username) AS number \nFROM "UserActivityStat" \nWHERE "UserActivityStat".timestamp BETWEEN convert_tz(?, ?, ?) AND convert_tz(?, ?, ?) GROUP BY date(convert_tz("UserActivityStat".timestamp, ?, ?)) ORDER BY timestamp'] [parameters: ('+00:00', '+00:00', '2018-08-27 00:00:00.000000', '+00:00', '+00:00', '2018-09-02 23:59:59.000000', '+00:00', '+00:00', '+00:00', '+00:00')]

**Comment by freeplant** [comment]
Pro edition only support MySQL database.

**Comment by tschoesi** [comment]
Then why is the `seafevents.conf` preconfigured with a sqlite3 db for the pro docker container (in the newest version also)?
```
[DATABASE]
type = sqlite3
path = /opt/seafile/pro-data/seafevents.db
```
