### ISSUE TITLE
/api2/ping/ fails with "TypeError: context must be a dict rather than RequestContext."

### ISSUE THREAD

**Issue by allo-** [haiwen/seahub#2368]
I noticed my client stopped syncing with my own server. When I visit the ping site (the client logs a problem there), it tells me:

    Sorry, but the requested page is unavailable due to a server hiccup.

And the log on the server side contains the backtrace:

```
2018-09-13 18:28:21,842 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api2/ping/
Traceback (most recent call last):
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/rest_framework/renderers.py", line 676, in render
    ret = template.render(context)
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/home/seafile/seafile-server-6.3.3/seahub/thirdpart/django/template/context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than RequestContext.
```

I did not change anything before it happened and upgraded from 6.2.2 to 6.3.3 after it happened. The upgrade did not fix the issue.

**Comment by allo-** [comment]
This issue happens when I open the API-URL in the browser (and still happens), but the problem why the client did not sync anymore was related to the openssl version on my system.

**Comment by MrMoronIV** [comment]
This is actually the first call they suggest to make in their api tutorial / manual. Although it seems the rest of the api calls work fine, ah well, we'll just have to wait for a fix
