### ISSUE TITLE
Integration with OnlyOffice does not work

### ISSUE THREAD

**Issue by dbet1** [haiwen/seahub#2877]
I have installed OnlyOffice as described here: https://manual.seafile.com/deploy/only_office.html.

Now if I open a document that cannot edited (doc), I receive the error that the document cannot downloaded. If I open one that should be edited (docx, xlsx) the error is that the document cannot saved. The OK button in this error dialog does not work, I have to close the browser tab.

In this installation Seafile is normal installed and OnlyOffice is in a docker container.

Then I have testet with Seafile *and* OnlyOffice in a docker container. This way documents that cannot edited can be opened and are showed, editable documents have the same error as described above, but the OK butten is working and I can show the document after. But not change.

Where can I receive further informations about this problem? Are there any special logs with helpful information in there?

By the way: I tried the integration with LibreOffice Online. First with docker, which also not worked, second with a local installation of the packages from collabora/code. Now it works, but I want to have document editing with Only Office.

**Comment by dbet1** [comment]
I have found the logs that report the error in the docker container. After that I do an internet search about that and I found the fix: it is a problem with the docker image with certificates that are signed with a self sign ca-cert. I could disable that unauthorized documents were restricte and now I can open and edit a file.

**Comment by dbet1** [comment]
But now I have a new problem, as good is that! I think no one should use such products.
I cannot save the document, it gives the error -331. With this I cannot find in the internet.
The error is this:
[2019-01-25T08:29:12.766] [ERROR] nodeJS - sendServerRequest error: docId = 7b3ba124b8460f868889;url = https://seafile.example.com/onlyoffice/editor-callback/;data = {"key":"7b3ba124b8460f868889","status":6,"url":"https://seafile.example.com/onlyofficeds/cache/files/7b3ba124b8460f868889_5685/output.xlsx/output.xlsx?md5=UQ3LuXXUELdiWAythBSI-Q==&expires=1548405853&disposition=attachment&ooname=output.xlsx","changesurl":"https://seafile.example.com/onlyofficeds/cache/files/7b3ba124b8460f868889_5685/changes.zip/changes.zip?md5=OcWStRB6vMC1vPfbBZ5fyw==&expires=1548405853&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.2.6","changes":[{"created":"2019-01-25 08:25:42","user":{"id":"uid-1548404649378","name":"user"}}]},"users":["uid-1548404649378"],"lastsave":"2019-01-25T08:28:41.425Z","forcesavetype":1}
Error: Error response: statusCode:500 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Page unavailable</title>
</head>
<body>
    <h1>Page unavailable</h1>

    <p>Sorry, but the requested page is unavailable due to a server hiccup.</p>

    <p>Our engineers have been notified, so check back later.</p>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
![fehler -331](https://user-images.githubusercontent.com/25152031/51739061-e0c69180-2090-11e9-8964-29b2ecf6b492.png)

**Comment by dbet1** [comment]
If I configure Seafile without HTTPS, then document editing works fine. I tried to switch to HTTPS again, but then I cannot call OnlyOffice in HTTP mode, it always loads a page with HTTPS, witch is empty. Then I can change https:// to http:// and document edititing works again.
But this is not a way for end users.

**Comment by freeplant** [comment]
This is likely your config problem.

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com
