### ISSUE TITLE
api2/search-user broken in recent releases

### ISSUE THREAD

**Issue by Nimloth** [haiwen/seahub#3001]
On a newer seafile install, I go to

System Admin => Libraries

and then for any library open the Share dialog.

In the search field, I can enter a username or email to search for a user to share the library with, but I always get a 'Loading failed' error.
The corresponding error in seahub.log is:

```
2019-02-25 17:35:06,946 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api2/search-user/
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
   response = get_response(request)
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
   response = self._get_response(request)
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
   return view_func(*args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
   return self.dispatch(request, *args, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 495, in dispatch
   response = self.handle_exception(exc)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 455, in handle_exception
   self.raise_uncaught_exception(exc)
 File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 492, in dispatch
   response = handler(request, *args, **kwargs)
 File "/usr/local/www/haiwen/seafile-server/seahub/seahub/api2/endpoints/search_user.py", line 129, in get
   user_obj_list = ccnet_api.get_emailusers_in_list('DB', email_list_json) + \
AttributeError: 'CcnetAPI' object has no attribute 'get_emailusers_in_list'

```
Versions:

ccnet 6.3.4
libsearpc 3.1.0
seafile-server 6.3.4
seahub 6.3.11
seafobj 6.3.11
seafdav 6.3.11

On an older install, this does not happen:

ccnet 6.3.4
libsearpc 3.0.8
seafile-server 6.3.4
seahub 6.3.7
seafobj 6.3.7
seafdav 6.3.7

Could this be related to [commit 4bd9c13927151b7c7688153d24552bf6d97c0a04](https://github.com/haiwen/seahub/pull/2633/commits/4bd9c13927151b7c7688153d24552bf6d97c0a04)?

**Comment by Ultima1252** [comment]
My inital scan was incorrect. The commit that introduced this regression is https://github.com/haiwen/seahub/commit/496b1c955f24be4ccaa285c70d4bed9794ca70c4 which was introduced in 6.3.8. Reverting the commit will restore fuctionality of this feature.
