### ISSUE TITLE
Seahub exception

### ISSUE THREAD

**Issue by monochromec** [haiwen/seahub#309]
seahub throws exception in urls.py (version 4.0.1):

2014/11/30 11:31:20 [error] 11866#0: *54 FastCGI sent in stderr: "" while reading response header from upstream, client: 192.168.2.1, server: www.example.com, request: "GET /vtigercrm/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "79.214.246.219"
2014/11/30 11:31:20 [error] 11866#0: *54 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/flup-1.0.3.dev_20110405-py2.7.egg/flup/server/fcgi_base.py", line 574, in run
    protocolStatus, appStatus = self.server.handler(self)
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/flup-1.0.3.dev_20110405-py2.7.egg/flup/server/fcgi_base.py", line 1159, in handler
    result = self.application(environ, start_response)
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 255, in **call**
    response = self.get_response(request)
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/core/handlers/base.py", line 178, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/core/handlers/base.py", line 220, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/utils/importlib.py", line 36, in import_module
    __import__(name)
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/Djblets-0.6.14-py2.7.egg/djblets/util/rooturl.py", line 40, in <module>
    (r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/conf/urls/**init**.py", line 25, in include
    urlconf_module = import_module(urlconf_module)
  File "/mnt/disk/seafile/.virtualenvs/vpyenv4/lib/python2.7/site-packages/django/utils/importlib.py", line 36, in import_module
    **import**(name)
  File "/mnt/disk/seafile.4/seafile-server/seahub/seahub/urls

Unfortunately seahub.error.log stops printing information here. More than happy to supply additional information if I would know how.

**Comment by freeplant** [comment]
This issue is obsolete.
