### ISSUE TITLE
Transfer a's repo to b by admin user failed

### ISSUE THREAD

**Issue by szimszon** [haiwen/seahub#339]
Hi!

I wonder if somebody could help me.

I would like to transfer a library owned by a to b with admin user but I got this:

Environment:

Request Method: POST
Request URL: http://*******/sys/seafadmin/transfer/

Django Version: 1.5.1
Python Version: 2.6.6
Installed Applications:
('django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'registration',
 'captcha',
 'seahub.api2',
 'seahub.avatar',
 'seahub.base',
 'seahub.contacts',
 'seahub.wiki',
 'seahub.group',
 'seahub.message',
 'seahub.notifications',
 'seahub.options',
 'seahub.profile',
 'seahub.share',
 'seahub.help',
 'seahub.thumbnail',
 'gunicorn')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'seahub.auth.middleware.AuthenticationMiddleware',
 'seahub.base.middleware.BaseMiddleware',
 'seahub.base.middleware.InfobarMiddleware')

Traceback:
File "/***/seafile-server-4.0.4/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py" in get_response
  115.                         response = callback(request, *callback_args, **callback_kwargs)
File "/***/seafile-server-4.0.4/seahub/seahub/auth/decorators.py" in _wrapped_view
  26.                 return view_func(request, *args, **kwargs)
File "/***/seafile-server-4.0.4/seahub/seahub/base/decorators.py" in _decorated
  20.             return func(request, *args, **kwargs)
File "/***/seafile-server-4.0.4/seahub/seahub/views/sysadmin.py" in sys_repo_transfer
  1098.         if seafserv_threaded_rpc.get_org_id_by_repo_id(repo_id) > 0:
File "/***/seafile-server-4.0.4/seafile/lib/python2.6/site-packages/pysearpc/client.py" in newfunc
  112.                 return fret(ret_str)
File "/***/seafile-server-4.0.4/seafile/lib/python2.6/site-packages/pysearpc/client.py" in _fret_int
  11.         raise SearpcError(dicts['err_msg'])

Exception Type: SearpcError at /sys/seafadmin/transfer/
Exception Value: cannot find function seafile_get_org_id_by_repo_id.

**Comment by bardamatic** [comment]
I am having the same issue but with 4.0.5
Traceback (most recent call last):
  File "/***/seafile-server-4.0.5/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/***/seafile-server-4.0.5/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/***/seafile-server-4.0.5/seahub/seahub/base/decorators.py", line 20, in _decorated
    return func(request, *args, **kwargs)
  File "/***/seafile-server-4.0.5/seahub/seahub/views/sysadmin.py", line 1147, in sys_repo_transfer
    if seafserv_threaded_rpc.get_org_id_by_repo_id(repo_id) > 0:
  File "/***/seafile-server-4.0.5/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 112, in newfunc
    return fret(ret_str)
  File "/***/seafile-server-4.0.5/seafile/lib64/python2.6/site-packages/pysearpc/client.py", line 11, in _fret_int
    raise SearpcError(dicts['err_msg'])
SearpcError: cannot find function seafile_get_org_id_by_repo_id.

**Comment by xiez** [comment]
Hi guys, this bug is confirmed in 4.0.5 server, it will be fixed in next release. 

Many thanks!
