### ISSUE TITLE
User get Page unavailable just after login

### ISSUE THREAD

**Issue by JeanLouPtflbx** [haiwen/seahub#3412]
After ugrade to seafile 6.3.4,
Some users, and freshly added user gets error just after loggin.
"Page unavailable
Sorry, but the requested page is unavailable due to a server hiccup.
Our engineers have been notified, so check back later."
They can go to profil page, when Url is enter in the browser.
Seafile client works as usual.

on serverside we got error like :
==> seahub.log <==
2019-05-06 08:53:40,553 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-6.3.4/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-6.3.4/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/seafile/seafile-server-6.3.4/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-server-6.3.4/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-6.3.4/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-6.3.4/seahub/seahub/base/decorators.py", line 40, in _decorated
    return func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-6.3.4/seahub/seahub/views/__init__.py", line 731, in libraries
    'can_add_public_repo': request.user.permissions.can_add_public_repo(),
  File "/opt/seafile/seafile-server-6.3.4/seahub/seahub/base/accounts.py", line 162, in can_add_public_repo
    elif get_enabled_role_permissions_by_role(self.user.role)['can_add_public_repo']:
KeyError: 'can_add_public_repo'

I try to stop seafile, delete /tmp/seahub_cache/ , restart without results

**Comment by JeanLouPtflbx** [comment]
Error on role definition.
