### ISSUE TITLE
access seahub return get http 1.1 500 368

### ISSUE THREAD

**Issue by walrusma** [haiwen/seahub#360]
access seahub via http://127.0.0.1 return error,how to fix it?

**Comment by walrusma** [comment]
detail seahub_django_request.log:
2015-01-30 16:21:20,116 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/data/haiwen/seafile-server/seahub/seahub/base/middleware.py", line 41, in process_request
    username)
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 184, in get_personal_groups_by_user
    groups_all = ccnet_threaded_rpc.get_groups(email)
  File "/usr/local/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/local/lib/python2.7/dist-packages/ccnet/rpc.py", line 71, in call_remote_func_sync
    client = self.pool.get_client()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/pool.py", line 27, in get_client
    client = self._create_client()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/pool.py", line 19, in _create_client
    client.connect_daemon()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/client.py", line 120, in connect_daemon
    return self.connect_daemon_with_pipe()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/client.py", line 102, in connect_daemon_with_pipe
    raise NetworkError("Can't connect to daemon")
NetworkError: Can't connect to daemon
2015-01-30 16:21:20,324 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/data/haiwen/seafile-server/seahub/seahub/base/middleware.py", line 41, in process_request
    username)
  File "/usr/local/lib/python2.7/dist-packages/seaserv/service.py", line 184, in get_personal_groups_by_user
    groups_all = ccnet_threaded_rpc.get_groups(email)
  File "/usr/local/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/local/lib/python2.7/dist-packages/ccnet/rpc.py", line 71, in call_remote_func_sync
    client = self.pool.get_client()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/pool.py", line 27, in get_client
    client = self._create_client()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/pool.py", line 19, in _create_client
    client.connect_daemon()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/client.py", line 120, in connect_daemon
    return self.connect_daemon_with_pipe()
  File "/usr/local/lib/python2.7/dist-packages/ccnet/client.py", line 102, in connect_daemon_with_pipe
    raise NetworkError("Can't connect to daemon")
NetworkError: Can't connect to daemon

**Comment by lins05** [comment]
From the logs I see your seafile server is in /data/haiwen/, but why do you
have files like /usr/local/lib/python2.7/dist-packages/ccnet/client.py
installed? Try uninstall/clean those files under /usr/local, and restart
seahub.

**Comment by walrusma** [comment]
It is resolved because of lack of some python libraries.
