### ISSUE TITLE
seafilepro 7.0.5 TypeError: create_repo() got multiple values for keyword argument 'enc_version'

### ISSUE THREAD

**Issue by graywen24** [haiwen/seahub#4182]
Hi,
  I tested many times, if I set ENABLE_STORAGE_CLASSES=True and configure the class policy to either "USER_SELECT" or "ROLE_BASED". Will encounter the error
TypeError: create_repo() got multiple values for keyword argument 'enc_version'

==> seahub.log output <==
> ==> seahub.log <==
2019-10-23 07:51:31,224 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /api2/repos/
Traceback (most recent call last):
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/seafile/seafile-pro-server-7.0.5/seahub/seahub/api2/base.py", line 23, in dispatch
    response = super(APIView, self).dispatch(*a, **kw)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/seafile/seafile-pro-server-7.0.5/seahub/seahub/api2/base.py", line 20, in handle_exception
    return super(APIView, self).handle_exception(exc)
  File "/seafile/seafile-pro-server-7.0.5/seahub/thirdpart/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/seafile/seafile-pro-server-7.0.5/seahub/seahub/api2/views.py", line 950, in post
    repo_id, error = self._create_repo(request, repo_name, repo_desc, username, org_id)
  File "/seafile/seafile-pro-server-7.0.5/seahub/seahub/api2/views.py", line 1006, in _create_repo
    enc_version=settings.ENCRYPTED_LIBRARY_VERSION)
TypeError: create_repo() got multiple values for keyword argument 'enc_version'

below is my configuration:

> seahub_settings.py
ENABLE_STORAGE_CLASSES = True
STORAGE_CLASS_MAPPING_POLICY = ‘USER_SELECT’
#STORAGE_CLASS_MAPPING_POLICY = ‘REPO_ID_MAPPING’
#STORAGE_CLASS_MAPPING_POLICY = ‘ROLE_BASED’
ENABLED_ROLE_PERMISSIONS = {
‘default’: {
‘can_add_repo’: True,
‘can_add_group’: True,
‘can_view_org’: True,
‘can_use_global_address_book’: True,
‘can_generate_share_link’: True,
‘can_generate_upload_link’: True,
‘can_invite_guest’: True,
‘can_connect_with_android_clients’: True,
‘can_connect_with_ios_clients’: True,
‘can_connect_with_desktop_clients’: True,
‘storage_ids’: [ ‘new_storage’, ‘cold_storage’,‘seafile-data’],

cat seafile_storage_classes.json
> [
{
“storage_id”: “seafile-data”,
“name”: “seafile-data”,
“is_default”: false,
“for_new_library”: false,
“fs”: {“backend”: “fs”, “dir”: “/seafile/seafile-data”},
“commits”: {“backend”: “fs”, “dir”: “/seafile/seafile-data”},
“blocks”: {“backend”: “fs”, “dir”: “/seafile/seafile-data”}
},
{
“storage_id”: “cold_storage”,
“name”: “cold_storage”,
“is_default”: false,
“for_new_library”: true,
“fs”: {“backend”: “fs”, “dir”: “/storage/seafile/cold_seafile-data”},
“commits”: {“backend”: “fs”, “dir”: “/storage/seafile/cold_seafile-data”},
“blocks”: {“backend”: “fs”, “dir”: “/storage/seafile/cold_seaflle-data”}
},
{
“storage_id”: “new_storage”,
“name”: “new_storage”,
“for_new_library”: true,
“is_default”: false,
“fs”: {“backend”: “fs”, “dir”: “/storage/seafile/new_seafile-data”},
“commits”: {“backend”: “fs”, “dir”: “/storage/seafile/new_seafile-data”},
“blocks”: {“backend”: “fs”, “dir”: “/storage/seafile/new_seafile-data”}
}

I do think there is some issue.

**Comment by graywen24** [comment]
Tested in 7.0.6 same error.. here is the way to pass the error 
edit file /seafile/seafile-pro-server-7.0.6/seahub/seahub/api2/views.py

`if STORAGE_CLASS_MAPPING_POLICY in ('USER_SELECT',
                        'ROLE_BASED'):

                    storages = get_library_storages(request)
                    storage_id = request.data.get("storage_id", None)
                    logger.info("====show current storage list ---->%s",storages )
                    if storage_id and storage_id not in [s['storage_id'] for s in storages]:
                        error_msg = 'storage_id invalid.'
                        return api_error(status.HTTP_400_BAD_REQUEST, error_msg)
                    repo_id = seafile_api.create_repo(repo_name,
                            repo_desc, username, passwd, storage_id)
                            #enc_version=settings.ENCRYPTED_LIBRARY_VERSION)   <--- comment this line`

**Comment by freeplant** [comment]
Will be fixed in 7.1 version.
