### ISSUE TITLE
v7.0.12-pro SSO-Login Error

### ISSUE THREAD

**Issue by cvantum** [haiwen/seahub#4411]
Hello,
we updated our SeaFile-Pro Server from 7.0.11-pro -> 7.0.12-pro. After Update the SSO-Login via SAML2/Shibboleth failed. In our log-files we found this error: 

```
2020-01-13 13:17:37,957 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /sso/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/shibboleth/middleware.py", line 87, in process_request
    user = auth.authenticate(remote_user=username, shib_meta=shib_meta)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/seahub/auth/__init__.py", line 56, in authenticate
    user = backend.authenticate(**credentials)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/shibboleth/backends.py", line 66, in authenticate
    return user
UnboundLocalError: local variable 'user' referenced before assignment
2020-01-13 13:17:44,767 [INFO] seafes:162 load_seafevents_conf [seafes] use highlighter fvh
2020-01-13 13:17:44,879 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /sso/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/shibboleth/middleware.py", line 87, in process_request
    user = auth.authenticate(remote_user=username, shib_meta=shib_meta)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/seahub/auth/__init__.py", line 56, in authenticate
    user = backend.authenticate(**credentials)
  File "/opt/seafile/seafile-pro-server-7.0.12/seahub/thirdpart/shibboleth/backends.py", line 66, in authenticate
    return user
UnboundLocalError: local variable 'user' referenced before assignment
```

We had to do a rollback to 7.0.11 to get a successfull login via SAML2/Shibboleth.

**Comment by freeplant** [comment]
Thanks for reporting the issue. The bug is fixed in 7.0.13.
