### ISSUE TITLE
Compairing files fails (Internal Server Error)

### ISSUE THREAD

**Issue by de-es** [haiwen/seahub#4429]
```
2020-02-06 10:44:03,576 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /repo/text_diff/53a11d60-409c-4799-b9a8-afba76ca7d6b/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1531, in _line_iterator
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/seafile/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/views/file.py", line 1670, in text_diff
    current_content.splitlines(), True)
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1991, in make_table
    fromlist, tolist, flaglist = self._collect_lines(diffs)
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1844, in _collect_lines
    for fromdata, todata, flag in diffs:
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1581, in _mdiff
    from_line, to_line, found_diff = next(line_pair_iterator)
  File "/opt/seafile/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1553, in _line_pair_iterator
    from_line, to_line, found_diff =next(line_iterator)
RuntimeError: generator raised StopIteration
```

This is on Seafile 7.1.1. 7.0.5 is working fine here.

**Comment by de-es** [comment]
Meanwhile the feature was completely removed in the 7.1 series. But I really don't understand why? I would appreciate a reappearance in the upcoming major release because it was a very useful feature for markdown or text files in general.

**Comment by de-es** [comment]
I guess this feature won't come back, so closing this ticket.
