### ISSUE TITLE
get groups by user fails in admin panel

### ISSUE THREAD

**Issue by Wenlong0913** [haiwen/seahub#4450]
`2020-02-26 11:45:20,049 [ERROR] seahub.api2.endpoints.admin.users:951 get 'CcnetAPI' object has no attribute 'get_personal_groups_by_user'`

<img width="1673" alt="Screen Shot 2020-02-26 at 20 16 02" src="https://user-images.githubusercontent.com/17941167/75344153-f120ef80-58d4-11ea-94f9-56c0dbe33bdf.png">

**Comment by freeplant** [comment]
What version do you use?

**Comment by Wenlong0913** [comment]
7.1.1

**Comment by Wenlong0913** [comment]
build seahub from current master branch

**Comment by Wenlong0913** [comment]
Btw, there is another issue I found today.
If I try `diff` md file's history, it will return 500 error.
Here is the logs:
```
2020-02-26 12:27:32,073 [WARNING] seahub.views:778 file_revisions Wrong type of suffix_list: None
2020-02-26 12:27:37,852 [ERROR] django.request:135 handle_uncaught_exception Internal Server Error: /repo/text_diff/42cc2f0f-c53e-4b66-9961-200047a7a81b/
Traceback (most recent call last):
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1531, in _line_iterator
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/thirdpart/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/views/file.py", line 1706, in text_diff
    current_content.splitlines(), True)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1991, in make_table
    fromlist, tolist, flaglist = self._collect_lines(diffs)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1844, in _collect_lines
    for fromdata, todata, flag in diffs:
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1581, in _mdiff
    from_line, to_line, found_diff = next(line_pair_iterator)
  File "/home/ubuntu/arima/drive/seafile-server-7.1.1/seahub/seahub/utils/htmldiff.py", line 1553, in _line_pair_iterator
    from_line, to_line, found_diff =next(line_iterator)
RuntimeError: generator raised StopIteration
```

**Comment by aeveris** [comment]
@freeplant I get the same error, as @Wenlong0913 when trying to access a users groups in the admin panel. Would you reopen this or should I open a new issue?

**Comment by axstet** [comment]
I get the same error on 7.1.3.

[ERROR] seahub.api2.endpoints.admin.users:1053 get 'CcnetAPI' object has no attribute 'get_p$
$'get_personal_groups_by_user'

I think line 1053 should call `get_groups` instead of `get_personal_groups_by_user`.
