### ISSUE TITLE
Internal Server Error after Upgrade from 7.0.x -> 7.1.3

### ISSUE THREAD

**Issue by cvantum** [haiwen/seahub#4555]
Hello,
we updated a CE-Server from 7.0.4 to 7.1.3. We followed the instruction page with installing new dependencies with Python3.7 on a Debian Stretch Server.

The Upgrade process ran as expected including but after we started the seahub-Service we got an internal server error. Running seahub-Service with command `seahub.sh` on CLI we got this error-message:

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/urls/resolvers.py", line 420, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/utils/rooturl.py", line 41, in <module>
    url(r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/urls.py", line 8, in <module>
    from seahub.views.sysadmin import *
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/views/sysadmin.py", line 13, in <module>
    from openpyxl import load_workbook
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
```
We didn't have any clue how to hotfix this problem. This server is already used as a productive service, so we had to rebuild a previous snapshot. If you need some additional informations we can only recap something from upgrade-process but not from the unworking system.

Hope this information are enough. Of cource if you need more additional informations we are trying to help

Thank you in advance.

Kind regards

**Comment by axstet** [comment]
Python 3.6 is required at least.
