### ISSUE TITLE
Long WebDAV Secret Yields 500 Error

### ISSUE THREAD

**Issue by oncomouse** [haiwen/seahub#4812]
I was trying to set a WebDAV secret in the latest version of seafile (8.0.3), when I found an error that briefly locked me out of the settings UI on seahub. TLDR: webdav secret appears to only be able to have a maximum length of 16 characters and the server will throw a 500 error if one longer than that is set. The maximum length should be enforced when generating a secret.

I set `ENABLE_WEBDAV_SECRET = True` in `seahub_settings.py`. In SeaHub's user settings, I set a long secret (32 characters), generated using a password manager. This results in an "Error" pop-up. Checking the AJAX request in developers tools, the call to the API results in a 500 error. Reloading the account settings page further yields a 500 error. Checking the error logs for SeaHub, the follow occurs:

```
2021-02-05 19:40:07,361 [ERROR] django.request:228 log_response Internal Server Error: /profile/
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-server-8.0.3/seahub/seahub/auth/decorators.py", line 27, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/seafile/seafile-server-8.0.3/seahub/seahub/profile/views.py", line 82, in edit_profile
    decoded = UserOptions.objects.get_webdav_decoded_secret(username)
  File "/opt/seafile/seafile-server-8.0.3/seahub/seahub/options/models.py", line 268, in get_webdav_decoded_secret
    decoded = aes.decode(secret)
  File "/opt/seafile/seafile-server-8.0.3/seahub/seahub/utils/hasher.py", line 54, in decode
    return DecodeAES(self.cipher, data)
  File "/opt/seafile/seafile-server-8.0.3/seahub/seahub/utils/hasher.py", line 30, in <lambda>
    DecodeAES = lambda c, e: c.decrypt(base64.b64decode(e)).decode('utf-8').rstrip(PADDING)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

It looks like [in hasher.py](https://github.com/haiwen/seahub/blob/632e98ccd657d6c312480768a7942ab50cae12e7/seahub/utils/hasher.py#L25) that a secret of maximum 16 characters is expected, but nothing in the UI actually checks that.

I was able to remove the too long secret from the MySQL database for my Seahub and setting a shorter secret works.

Just wanted to pass along that this is an error; it looks like a maximum password length should be set in the UI for user settings.

**Comment by freeplant** [comment]
A fix will be included in the next release.
