### ISSUE TITLE
AttributeError: 'QuerySet' object has no attribute 'institution'

### ISSUE THREAD

**Issue by moschlar** [haiwen/seahub#5027]
seafile-pro-server-7.1.22:

```
2021-11-10 20:34:03,235 [ERROR] django.request:228 log_response Internal Server Error: /api/v2.1/admin/search-user/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/thirdpart/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/seafile/seafile-pro-server-8.0.12/seahub/seahub/api2/endpoints/admin/users.py", line 910, in get
    user.institution = profile.institution
AttributeError: 'QuerySet' object has no attribute 'institution'
```

**Comment by moschlar** [comment]
fixed in #5043
