### ISSUE TITLE
Bug: Error when logging in with keycloak 20. Userinfo is None

### ISSUE THREAD

**Issue by ykorzikowski** [haiwen/seahub#5311]
Error happens, when I try to use single-sign-on. The Keycloak-Auth is working, but during callback there is an error. Looks like it happens when seafile is calling the userinfo-api. 

It was working with Keycloak 17. 

- Keycloak 20
- Seafile Server 9.0.5

![grafik](https://user-images.githubusercontent.com/20556547/202428347-0541d4c1-038f-43f0-9e72-84e6fcdbee33.png)

This is the keycloak-log:

```
2022-11-17 11:19:38,131 WARN  [org.keycloak.events] (executor-thread-30) type=USER_INFO_REQUEST_ERROR, realmId=master, clientId=null, userId=null, ipAddress=10.10.10.101, error=access_denied, auth_method=validate_access_token
```

```

2022-11-17 10:55:52,387 [INFO] seahub.oauth.views:156 format_user_info user info resp:
2022-11-17 10:55:52,387 [ERROR] django.request:224 log_response Internal Server Error: /oauth/callback/
Traceback (most recent call last):
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/haiwen/seafile-server-9.0.9/seahub/seahub/oauth/views.py", line 87, in _decorated
    return func(request)
  File "/haiwen/seafile-server-9.0.9/seahub/seahub/oauth/views.py", line 177, in oauth_callback
    user_info, error = format_user_info(user_info_resp)
  File "/haiwen/seafile-server-9.0.9/seahub/seahub/oauth/views.py", line 159, in format_user_info
    user_info_json = user_info_resp.json()
  File "/haiwen/seafile-server-9.0.9/seahub/thirdpart/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

```

My Investigation: 

The userinfo is empty for some reason: 

https://github.com/haiwen/seahub/blob/4d38b499411012e963d6381731260e1ef06174b5/seahub/oauth/views.py#L159

This should be caught by try/catch. 

Additionally, Keycloak removed deprecated stuff during version 18-20. I think, some access_token handling changed, so the userinfo-request is unauthenticated. Maybe related to this comment https://github.com/oauth2-proxy/oauth2-proxy/issues/1216#issuecomment-857086005

**Comment by ykorzikowski** [comment]
Originally opened here: https://github.com/haiwen/seafile/issues/2621

**Comment by ykorzikowski** [comment]
Possible fix for better error message: 

```
        user_info_json = {}

        try:
            user_info_json = user_info_resp.json()
        except Exception as e:
            logger.error("Userinfo is empty")

```

**Comment by nitinsmartsense** [comment]
Please check [this](https://keycloak.discourse.group/t/issue-on-userinfo-endpoint-at-keycloak-20/18461).
You need to pass `openid` scope to the client.

**Comment by ykorzikowski** [comment]
Hey @nitinsmartsense , 

this fixed the error for me :) thanks

So I added a new client scope called `openid` and added it to default client scope in seafile. 

I had to chage my `seahub_settings.py` and add "openid" to scopes:

```
OAUTH_SCOPE = ["profile", "openid", "email"]
```
