### ISSUE TITLE
seafile-pro-server-4.2.0 integration with Shibboleth SP for SSO authorization

### ISSUE THREAD

**Issue by rabb1t** [haiwen/seahub#626]
I'm trying to setup SSO for `seafile-pro-server-4.2.0` with `Shibboleth` software as SP.
Everything works fine until I've got the `'seahub_auth'` cookie. When this happens authorization immediately fails with the error below:

> 2015-06-03 13:29:16,458 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /shib-login/
Traceback (most recent call last):
  File "/opt/seafile/seafile-pro-server-4.2.0/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/opt/seafile/seafile-pro-server-4.2.0/seahub/thirdpart/shibboleth/middleware.py", line 59, in process_request
    " not found.  %s" % shib_meta)
ShibbolethValidationError: All required Shibboleth elements not found.  {'username': ''}

It seems that shibboleth's middleware can't get username from that cookie. Moreover I can't find any lines of code when this cookie are parsed:

> rabbit@seaf1 /opt/seafile # grep seahub_auth /opt/seafile/seafile-pro-server-4.2.0/seahub/thirdpart/shibboleth/middleware.py
        response.set_cookie('seahub_auth', request.user.username + '@' + token.key)

> rabbit@seaf1 /opt/seafile # grep cookie /opt/seafile/seafile-pro-server-4.2.0/seahub/thirdpart/shibboleth/middleware.py
            print '%s: set shibboleth cookie!' % id(self)
            self._set_auth_cookie(request, response)
    def _set_auth_cookie(self, request, response):
        response.set_cookie('seahub_auth', request.user.username + '@' + token.key)

> rabbit@seaf1 /opt/seafile # grep seahub_auth /opt/seafile/seafile-pro-server-4.2.0/ -r -l
seafile-pro-server-4.2.0/seahub/thirdpart/shibboleth/middleware.py
seafile-pro-server-4.2.0/seahub/thirdpart/shibboleth/middleware.pyc

**Comment by shoeper** [comment]
Did you have a look at http://manual.seafile.com/deploy/shibboleth_config.html?

**Comment by rabb1t** [comment]
Sure.

The main problem is that when you have a `'seahub_auth'` cookie set there are no any requests to shibboleth auth module so therefore 'REMOTE_USER' variable is always empty and authorization fails with `ShibbolethValidationError: All required Shibboleth elements not found. {'username': ''}` error.

Finally I got it to work only by modifying these files:

/opt/seafile/seafile-server-latest/seahub/thirdpart/shibboleth/app_settings.py

>-SHIB_USER_HEADER = getattr(settings, 'SHIBBOLETH_USER_HEADER', "REMOTE_USER")
+SHIB_USER_HEADER = getattr(settings, 'SHIBBOLETH_USER_HEADER', "HTTP_EPPN")

/srv/seafile/seahub_settings.py
>SHIBBOLETH_ATTRIBUTE_MAP = {
    "HTTP_EPPN": (True, "username"),
}

Because `HTTP_EPPN` variable is always set. But I think this isn't the proper way.

**Comment by killing** [comment]
Hi @rabb1t 
In Seafile, Shibboleth is only used when the user logs in via https://your-server/shib-login. After the user has logged in, Shibboleth is not involved any more. After that users log in to seahub with cookie. Put it another way, we by-pass Shibboleth after the first log in.

**Comment by rabb1t** [comment]
Yes, the problem appears only when you trying to login.

I've tried to investigate this problem more deeply and found very strange things.
Sometimes the variable `'REMOTE_USER'` processed correctly but sometimes it's not. Nginx's log files indicates that shibboleth daemon provides header `'Variable-REMOTE_USER'` correctly and the shibboleth module also copies it `shib request authorizer copied header: "REMOTE_USER: vasya.pupkin@local.lan"`

But periodically it seems that somehow this header isn't transmitted properly further to Nginx.
Any help on this problem will be appreciated!

Here are the cut of nginx error.log files:
* Authorization is granted:
```
: *3 try files phase: 14
: *3 http init upstream, client timer: 0
: *3 http script copy: "SCRIPT_FILENAME"
: *3 http script var: "/etc/nginx/html"
: *3 http script var: "/shib-login/"
: *3 fastcgi param: "SCRIPT_FILENAME: /etc/nginx/html/shib-login/"
: *3 http script copy: "PATH_INFO"
: *3 http script var: "/shib-login/"
: *3 fastcgi param: "PATH_INFO: /shib-login/"
: *3 http script copy: "HTTPS"
: *3 http script copy: "on"
: *3 fastcgi param: "HTTPS: on"
: *3 http script copy: "HTTP_SCHEME"
: *3 http script copy: "https"
: *3 fastcgi param: "HTTP_SCHEME: https"
: *3 http script copy: "SERVER_PROTOCOL"
: *3 http script var: "HTTP/1.1"
: *3 fastcgi param: "SERVER_PROTOCOL: HTTP/1.1"
: *3 http script copy: "QUERY_STRING"
: *3 http script var: "next=/home/my/"
: *3 fastcgi param: "QUERY_STRING: next=/home/my/"
: *3 http script copy: "REQUEST_METHOD"
: *3 http script var: "GET"
: *3 fastcgi param: "REQUEST_METHOD: GET"
: *3 http script copy: "CONTENT_TYPE"
: *3 fastcgi param: "CONTENT_TYPE: "
: *3 http script copy: "CONTENT_LENGTH"
: *3 fastcgi param: "CONTENT_LENGTH: "
: *3 http script copy: "SERVER_ADDR"
: *3 http script var: "192.168.231.224"
: *3 fastcgi param: "SERVER_ADDR: 192.168.231.224"
: *3 http script copy: "SERVER_PORT"
: *3 http script var: "443"
: *3 fastcgi param: "SERVER_PORT: 443"
: *3 http script copy: "SERVER_NAME"
: *3 http script var: "seafile.local.lan"
: *3 fastcgi param: "SERVER_NAME: seafile.local.lan"
: *3 http script copy: "REMOTE_ADDR"
: *3 http script var: "192.168.230.1"
: *3 fastcgi param: "REMOTE_ADDR: 192.168.230.1"
: *3 http script copy: "CLIENT_CERTIFICATE"
: *3 fastcgi param: "CLIENT_CERTIFICATE: "
: *3 http script copy: "REMOTE_USER"                     <=====8=== NOT EMPTY!
: *3 http script var: "john.doe@local.lan"               <=====8=== NOT EMPTY!
: *3 fastcgi param: "REMOTE_USER: john.doe@local.lan"
: *3 fastcgi param: "HTTP_HOST: seafile.local.lan"
: *3 fastcgi param: "HTTP_CONNECTION: keep-alive"
: *3 fastcgi param: "HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
: *3 fastcgi param: "HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"
: *3 fastcgi param: "HTTP_DNT: 1"
: *3 fastcgi param: "HTTP_REFERER: https://seafile.local.lan/accounts/login/?next=/home/my/"
: *3 fastcgi param: "HTTP_ACCEPT_ENCODING: gzip, deflate, sdch"
: *3 fastcgi param: "HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.8,ru;q=0.6"
: *3 fastcgi param: "HTTP_COOKIE: _shibsession_64656661756c7468747470733a2f2f626f782e6b6173706572736b792e636f6d2f736869622d6c6f67696e2f=_4c17973813a257c94b21c7289995784a; seahub_auth="john.doe@local.lan@74ff75de607924e25c2cc781536ead324f1a4686"; csrftoken=56tYHbERpghhXplnJAwUVr9DMd5wKzL3; sessionid=mivnupl0aj5kj470jiv8vww8j1ivx81s"
: *3 fastcgi param: "HTTP_AUTH_TYPE: shibboleth"
: *3 fastcgi param: "HTTP_REMOTE_USER: john.doe@local.lan"
: *3 fastcgi param: "HTTP_SHIB_APPLICATION_ID: default"
: *3 fastcgi param: "HTTP_SHIB_AUTHENTICATION_INSTANT: 2015-06-10T08:01:42.467Z"
: *3 fastcgi param: "HTTP_SHIB_AUTHENTICATION_METHOD: urn:federation:authentication:windows"
: *3 fastcgi param: "HTTP_SHIB_AUTHNCONTEXT_CLASS: urn:federation:authentication:windows"
: *3 fastcgi param: "HTTP_SHIB_IDENTITY_PROVIDER: https://sts.local.lan/adfs/services/trust"
: *3 fastcgi param: "HTTP_SHIB_SESSION_ID: _4c17973813a257c94b21c7289995784a"
: *3 fastcgi param: "HTTP_EPPN: john.doe@local.lan"
: *3 http cleanup add: 0000000001467A30
: *3 get rr peer, try: 1
: *3 socket 16
: *3 epoll add connection: fd:16 ev:80002005
: *3 connect to 127.0.0.1:8000, fd:16 #3
: *3 http upstream connect: -2
: *3 posix_memalign: 00000000013B1E50:128 @16
: *3 event timer add: 16: 60000:1433934768775
: *3 http finalize request: -4, "/shib-login/?next=/home/my/" a:1, c:2
: *3 http request count:2 blk:0
```
* Authorization is not granted:
```
: *3 shib request handler
: *3 shib request set variables
: *3 shib request authorizer handler
: *3 shib request authorizer allows access
: *3 shib request authorizer copied header: "AUTH_TYPE: shibboleth"
: *3 shib request authorizer copied header: "REMOTE_USER: john.doe@local.lan"
: *3 shib request authorizer copied header: "Shib-Application-ID: default"
: *3 shib request authorizer copied header: "Shib-Authentication-Instant: 2015-06-10T08:01:42.467Z"
: *3 shib request authorizer copied header: "Shib-Authentication-Method: urn:federation:authentication:windows"
: *3 shib request authorizer copied header: "Shib-AuthnContext-Class: urn:federation:authentication:windows"
: *3 shib request authorizer copied header: "Shib-Identity-Provider: https://sts.local.lan/adfs/services/trust"
: *3 shib request authorizer copied header: "Shib-Session-ID: _4c17973813a257c94b21c7289995784a"
: *3 shib request authorizer copied header: "eppn: john.doe@local.lan"
: *3 fastcgi param: "PATH_INFO: /shib-login/"
: *3 http script copy: "HTTPS"
: *3 http script copy: "on"
: *3 fastcgi param: "HTTPS: on"
: *3 http script copy: "HTTP_SCHEME"
: *3 http script copy: "https"
: *3 fastcgi param: "HTTP_SCHEME: https"
: *3 http script copy: "SERVER_PROTOCOL"
: *3 http script var: "HTTP/1.1"
: *3 fastcgi param: "SERVER_PROTOCOL: HTTP/1.1"
: *3 http script copy: "QUERY_STRING"
: *3 http script var: "next=/home/my/"
: *3 fastcgi param: "QUERY_STRING: next=/home/my/"
: *3 http script copy: "REQUEST_METHOD"
: *3 http script var: "GET"
: *3 fastcgi param: "REQUEST_METHOD: GET"
: *3 http script copy: "CONTENT_TYPE"
: *3 fastcgi param: "CONTENT_TYPE: "
: *3 http script copy: "CONTENT_LENGTH"
: *3 fastcgi param: "CONTENT_LENGTH: "
: *3 http script copy: "SERVER_ADDR"
: *3 http script var: "192.168.231.224"
: *3 fastcgi param: "SERVER_ADDR: 192.168.231.224"
: *3 http script copy: "SERVER_PORT"
: *3 http script var: "443"
: *3 fastcgi param: "SERVER_PORT: 443"
: *3 http script copy: "SERVER_NAME"
: *3 http script var: "seafile.local.lan"
: *3 fastcgi param: "SERVER_NAME: seafile.local.lan"
: *3 http script copy: "REMOTE_ADDR"
: *3 http script var: "192.168.230.1"
: *3 fastcgi param: "REMOTE_ADDR: 192.168.230.1"
: *3 http script copy: "CLIENT_CERTIFICATE"
: *3 fastcgi param: "CLIENT_CERTIFICATE: "
: *3 http script copy: ""                        <=====8=== IS EMPTY!
: *3 fastcgi param: "HTTP_HOST: seafile.local.lan"
: *3 fastcgi param: "HTTP_CONNECTION: keep-alive"
: *3 fastcgi param: "HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
: *3 fastcgi param: "HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"
: *3 fastcgi param: "HTTP_DNT: 1"
: *3 fastcgi param: "HTTP_REFERER: https://seafile.local.lan/accounts/login/?next=/home/my/"
: *3 fastcgi param: "HTTP_ACCEPT_ENCODING: gzip, deflate, sdch"
: *3 fastcgi param: "HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.8,ru;q=0.6"
: *3 fastcgi param: "HTTP_COOKIE: _shibsession_64656661756c7468747470733a2f2f626f782e6b6173706572736b792e636f6d2f736869622d6c6f67696e2f=_4c17973813a257c94b21c7289995784a; seahub_auth="john.doe@local.lan@74ff75de607924e25c2cc781536ead324f1a4686"; csrftoken=56tYHbERpghhXplnJAwUVr9DMd5wKzL3; sessionid=g6i8v2hd4qy0ftzfsguosdm5wk6kw2n8"
: *3 fastcgi param: "HTTP_AUTH_TYPE: shibboleth"
: *3 fastcgi param: "HTTP_REMOTE_USER: john.doe@local.lan"
: *3 fastcgi param: "HTTP_SHIB_APPLICATION_ID: default"
: *3 fastcgi param: "HTTP_SHIB_AUTHENTICATION_INSTANT: 2015-06-10T08:01:42.467Z"
: *3 fastcgi param: "HTTP_SHIB_AUTHENTICATION_METHOD: urn:federation:authentication:windows"
: *3 fastcgi param: "HTTP_SHIB_AUTHNCONTEXT_CLASS: urn:federation:authentication:windows"
: *3 fastcgi param: "HTTP_SHIB_IDENTITY_PROVIDER: https://sts.local.lan/adfs/services/trust"
: *3 fastcgi param: "HTTP_SHIB_SESSION_ID: _4c17973813a257c94b21c7289995784a"
: *3 fastcgi param: "HTTP_EPPN: john.doe@local.lan"
: *3 http cleanup add: 0000000001EDFA00
: *3 get rr peer, try: 1
: *3 socket 20
: *3 epoll add connection: fd:20 ev:80002005
: *3 connect to 127.0.0.1:8000, fd:20 #9
: *3 http upstream connect: -2
: *3 posix_memalign: 0000000001EEB480:128 @16
: *3 event timer add: 20: 60000:1433934912565
: *3 http finalize request: -4, "/shib-login/?next=/home/my/" a:1, c:2
: *3 http request count:2 blk:0
```
