### ISSUE TITLE
500 Internal Server Error when creating private folder share

### ISSUE THREAD

**Issue by DevCybran** [haiwen/seahub#661]
Sharing a folder to a group or other user does not work for a particular folder. Seahub simply will never close the share overlay, but analyzing the HTTP response shows that actually a **500 Internal Server Error** is returned.

The folder to be shared is inside a non-encrypted, private library. A share link to the folder has been successfully created (possibly before a server update). The folder itself has the following path:
_Bibliotheken / Meine Bibliotheken / Studium / TU_Dresden / 2015_2015_SS / Bachelor Informatik / C++ für Computergraphik / CPP4CG-Artefakte /_
Sharing the parent folder works without problems.

The following log entry can be found in seahub_django_request.log:

```
2015-06-23 22:58:33,741 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /share/ajax/private-share-dir/
Traceback (most recent call last):
  File "/media/datastore/seafile/haiwen/seafile-server-4.2.3/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/media/datastore/seafile/haiwen/seafile-server-4.2.3/seahub/seahub/auth/decorators.py", line 69, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/media/datastore/seafile/haiwen/seafile-server-4.2.3/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/media/datastore/seafile/haiwen/seafile-server-4.2.3/seahub/seahub/share/views.py", line 1528, in ajax_private_share_dir
    shared_repo_id = sub_repo.id
AttributeError: 'NoneType' object has no attribute 'id'
```

Reproduced using seafile server 4.2.1 and 4.2.3.

**Comment by DevCybran** [comment]
Update: Sharing works when renaming this specific folder.

It is very likely that the folder has been shared to other users before, the share has been revoked and the folder's internal state somehow became corrupted.

**Comment by xiez** [comment]
hey, can u post detailed steps to reproduce this problem ? thanks a lot!

**Comment by DevCybran** [comment]
Sorry, since I do not know what originally caused the problem, I am not able to give detailed steps to reproduce the problem. The above mentioned steps are the only ones I can provide :(

**Comment by khorkin** [comment]
I have the same problem. I solve it by removing record from seafile.VirtualRepo.
```
| 7755cce8-39ee-4a3f-a43a-01c17eeccec0 | 833e2dc7-00ef-4263-9e03-82accda71d01 | /pictures                                                    | 13a85e7797b66bb3d6d0936d2c0b851b5628a8e0 |
```
```
MariaDB [seafile]> delete from VirtualRepo where repo_id = '7755cce8-39ee-4a3f-a43a-01c17eeccec0' and origin_repo = '833e2dc7-00ef-4263-9e03-82accda71d01';
Query OK, 1 row affected (0.19 sec)
```
Further I found that no records with the same repo_id in Repo and RepoOwner tables
```
MariaDB [seafile]> select * from RepoOwner where repo_id = '7755cce8-39ee-4a3f-a43a-01c17eeccec0';
Empty set (0.00 sec)

MariaDB [seafile]> select * from Repo where repo_id = '7755cce8-39ee-4a3f-a43a-01c17eeccec0';
Empty set (0.00 sec)
```
as should be if I has normal shared repo
```
MariaDB [seafile]> select * from Repo where repo_id = '474313b3-983e-4524-81c9-157ff36bf53f';
+--------------------------------------+
| repo_id                              |
+--------------------------------------+
| 474313b3-983e-4524-81c9-157ff36bf53f |
+--------------------------------------+
1 row in set (0.00 sec)

MariaDB [seafile]> select repo_id from RepoOwner where repo_id = '474313b3-983e-4524-81c9-157ff36bf53f';
+--------------------------------------+
| repo_id                              |
+--------------------------------------+
| 474313b3-983e-4524-81c9-157ff36bf53f |
+--------------------------------------+
1 row in set (0.00 sec)

MariaDB [seafile]> select * from VirtualRepo where repo_id = '474313b3-983e-4524-81c9-157ff36bf53f';
+--------------------------------------+--------------------------------------+-----------+------------------------------------------+
| repo_id                              | origin_repo                          | path      | base_commit                              |
+--------------------------------------+--------------------------------------+-----------+------------------------------------------+
| 474313b3-983e-4524-81c9-157ff36bf53f | 833e2dc7-00ef-4263-9e03-82accda71d01 | /pictures | 13a85e7797b66bb3d6d0936d2c0b851b5628a8e0 |
+--------------------------------------+--------------------------------------+-----------+------------------------------------------+
1 row in set (0.00 sec)
```

I may suggest that in my case the problem can be issued by high latency database, if modification all these tables performed separately, not in transaction.
