### ISSUE TITLE
[pro] seahub exception on FileUpdate page when user is None

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#880]
Hi,
in admin view "Logs", when choose File Update tab seahub may return exception (500 http error) if at least one record doesn't have real username.
It's possible as an valid example, when files was been added via "Upload Link" by anonymous user.
There is django exception:

```
2015-11-03 07:21:52,929 [ERROR] django.request:210 handle_uncaught_exception Internal Server Error: /sys/log/fileupdate/
Traceback (most recent call last):
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/seahub/auth/decorators.py", line 26, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/seahub/base/decorators.py", line 27, in _decorated
    return func(request, *args, **kwargs)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub-extra/seahub_extra/sysadmin_extra/views.py", line 163, in sys_log_file_update
    }, context_instance=RequestContext(request))
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 140, in render
    return self._render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 285, in render
    return nodelist.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/srv/seafile/seafile-pro-server-4.4.4/seahub/thirdpart/Django-1.5.12-py2.6.egg/django/template/defaulttags.py", line 426, in render
    raise e
NoReverseMatch: Reverse for 'user_info' with arguments '(u'',)' and keyword arguments '{}' not found.
```

**Comment by imwhatiam** [comment]
Thanks for reporting. We will fix it in the next version.
